name: Build All LaTeX Tutorials and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tutorial:
          - { path: "Tutorial1/src/tut1.tex", name: "Tutorial1" }
          - { path: "Tutorial2/src/tut2.tex", name: "Tutorial2" }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install additional packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pygments

      - name: Compile ${{ matrix.tutorial.name }}
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ matrix.tutorial.path }}
          compiler: pdflatex
          args: -shell-escape -interaction=nonstopmode
          pre_compile: |
            tlmgr update --self
            tlmgr install minted fvextra upquote
          post_compile: |
            echo "PDF compiled successfully"

      - name: Rename PDF
        run: |
          mkdir -p output
          find . -name "*.pdf" -exec cp {} output/${{ matrix.tutorial.name }}.pdf \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tutorial.name }}-pdf
          path: output/*.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Organize files for release
        run: |
          mkdir -p release-files
          find artifacts -name "*.pdf" -exec cp {} release-files/ \;
          ls -la release-files/

      - name: Create release with timestamp
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}-${{ github.sha }}
          name: "Tutorial Build ${{ github.run_number }}"
          body: |
            Automated build of LaTeX tutorials

            **Build Info:**
            - Build Number: ${{ github.run_number }}
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
            - Timestamp: ${{ github.event.head_commit.timestamp }}

            **Files included:**
            - Tutorial1.pdf
            - Tutorial2.pdf
          files: release-files/*.pdf
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
